// Generated by tools/export_arduino.py - do not edit, edit lib/ and src/ instead.
/**
 * @file debouncer.h
 * @brief Consecutive-sample filter for noisy digital inputs (level sensors).
 */
#ifndef CLARA_DEBOUNCER_H
#define CLARA_DEBOUNCER_H

#include <stdint.h>

namespace clara {

/**
 * The debounced state changes only after @c requiredSamples consecutive raw
 * samples disagree with it. Sample it at a fixed rate (e.g. 1 Hz) and the
 * filter time is requiredSamples / rate; a single contrary sample resets the
 * count. This replaces the v2.2 array-comparison code, which indexed past the
 * end of its buffers.
 */
class Debouncer {
 public:
  explicit Debouncer(uint8_t requiredSamples = 1, bool initialState = false)
      : required_(requiredSamples == 0 ? 1 : requiredSamples), count_(0), state_(initialState) {}

  void setRequiredSamples(uint8_t requiredSamples) {
    required_ = requiredSamples == 0 ? 1 : requiredSamples;
  }

  /** Forces the debounced state (e.g. at start-up). */
  void reset(bool state) {
    state_ = state;
    count_ = 0;
  }

  /** Feeds one raw sample and returns the (possibly updated) debounced state. */
  bool update(bool sample) {
    if (sample == state_) {
      count_ = 0;
    } else if (++count_ >= required_) {
      state_ = sample;
      count_ = 0;
    }
    return state_;
  }

  bool state() const { return state_; }

 private:
  uint8_t required_;
  uint8_t count_;
  bool state_;
};

}  // namespace clara

#endif  // CLARA_DEBOUNCER_H
