// Generated by tools/export_arduino.py - do not edit, edit lib/ and src/ instead.
/**
 * @file dosing_link.h
 * @brief I2C protocol between the main board (master) and the dosing board (slave).
 *
 * The main board polls the dosing board once per second with
 * Wire.requestFrom(kDosingBoardAddress, kTelemetryFrameSize). The dosing board
 * answers with one telemetry frame:
 *
 * | offset | size | field              | unit / meaning                                   |
 * |--------|------|--------------------|--------------------------------------------------|
 * | 0      | 1    | protocol version   | kProtocolVersion                                 |
 * | 1      | 1    | sequence           | increments with every new sample (stale check)   |
 * | 2      | 1    | status flags       | see StatusFlag                                   |
 * | 3      | 4    | flowLpm            | float, current water flow, L/min                 |
 * | 7      | 4    | lastDoseMl         | float, NaClO commanded in the last interval, mL  |
 * | 11     | 4    | totalWaterL        | uint32, water measured since power-up, L         |
 * | 15     | 4    | totalNaclOMicroL   | uint32, NaClO actually pumped since power-up, uL |
 * | 19     | 4    | targetFrcMgL       | float, configured free residual chlorine, mg/L   |
 * | 23     | 4    | uptimeS            | uint32, dosing board uptime, s                   |
 * | 27     | 1    | CRC-8 of bytes 0..26                                                   |
 *
 * All multi-byte fields are little endian. 28 bytes fit the 32-byte AVR Wire
 * buffer. The dosing board owns all dosing calibration (in its own EEPROM, set
 * from its own USB console), so no data flows from master to slave. v2.2 tried
 * to send the calibration from the main board, but the frame length never
 * matched what the slave accepted, so it was silently ignored.
 */
#ifndef CLARA_DOSING_LINK_H
#define CLARA_DOSING_LINK_H

#include <stdint.h>

namespace clara {
namespace link {

const uint8_t kDosingBoardAddress = 0x21;
const uint8_t kProtocolVersion = 3;
const uint8_t kTelemetryFrameSize = 28;

/** Bits of DosingTelemetry::flags. */
enum StatusFlag {
  kFlagChemicalAvailable = 1u << 0,  ///< NaClO level signal present, dosing enabled.
  kFlagPumpRunning = 1u << 1,        ///< Pump has steps queued.
  kFlagPumpSaturated = 1u << 2,      ///< Demand exceeded max pump speed: under-dosing!
  kFlagConfigDefaults = 1u << 3,     ///< Calibration not found in EEPROM, factory defaults in use.
  kFlagFlowSimulated = 1u << 4,      ///< Bench-test flow simulation is active.
  kFlagManualMode = 1u << 5,         ///< A manual pump test/calibration is running.
};

struct DosingTelemetry {
  uint8_t sequence;
  uint8_t flags;
  float flowLpm;
  float lastDoseMl;
  uint32_t totalWaterL;
  uint32_t totalNaclOMicroL;
  float targetFrcMgL;
  uint32_t uptimeS;
};

enum DecodeResult {
  kDecodeOk = 0,
  kDecodeBadLength,
  kDecodeBadVersion,
  kDecodeBadCrc,
};

/** Serialises @p telemetry into @p frame (kTelemetryFrameSize bytes). */
void encodeTelemetry(const DosingTelemetry& telemetry, uint8_t* frame);

/** Parses and validates a received frame. @p out is only written on success. */
DecodeResult decodeTelemetry(const uint8_t* frame, uint8_t length, DosingTelemetry& out);

}  // namespace link
}  // namespace clara

#endif  // CLARA_DOSING_LINK_H
