// Generated by tools/export_arduino.py - do not edit, edit lib/ and src/ instead.
/**
 * @file eeprom_store.h
 * @brief Checksummed EEPROM records: calibration parameters and a wear-levelled
 *        ring buffer for frequently updated state.
 */
#ifndef CLARA_EEPROM_STORE_H
#define CLARA_EEPROM_STORE_H

#include <stdint.h>

#include "param_store.h"

namespace clara {

/** Byte-addressable non-volatile memory. Implemented by the Arduino EEPROM on target and by a RAM array in tests. */
class EepromDevice {
 public:
  virtual uint8_t read(uint16_t address) const = 0;
  /** Writes only if the value differs (saves erase/write cycles). */
  virtual void update(uint16_t address, uint8_t value) = 0;
  virtual uint16_t size() const = 0;

 protected:
  ~EepromDevice() {}
};

/**
 * Stores a ParamStore as one record:
 *
 * | offset | size | content                       |
 * |--------|------|-------------------------------|
 * | 0      | 2    | magic 0x434C ("CL")           |
 * | 2      | 2    | ParamStore::schemaId(n)       |
 * | 4      | 1    | parameter count n             |
 * | 5      | 4n   | float values, little endian   |
 * | 5+4n   | 2    | CRC-16 of all preceding bytes |
 */
class ParamPersistence {
 public:
  enum LoadResult {
    kLoadOk = 0,         ///< Record valid, every value applied.
    kLoadRepaired,       ///< Record valid, but some values were out of range and were reset to defaults.
    kLoadExtended,       ///< Record from a firmware with fewer parameters: those values were kept, the
                         ///< new parameters got their defaults. Save to upgrade the record.
    kLoadEmpty,          ///< No record (blank or foreign data): defaults in use.
    kLoadSchemaChanged,  ///< Record written by a firmware with a different table: defaults in use.
    kLoadCorrupt,        ///< Checksum error: defaults in use.
  };

  ParamPersistence(EepromDevice& eeprom, uint16_t baseAddress) : eeprom_(eeprom), base_(baseAddress) {}

  /**
   * Loads the record into @p params. On any failure @p params is reset to
   * defaults. A record written by an older firmware whose table was a prefix of
   * the current one (parameters are only ever appended) is still accepted.
   */
  LoadResult load(ParamStore& params) const;

  /** Writes @p params. Only changed bytes are physically written. */
  void save(const ParamStore& params);

  /** Bytes of EEPROM occupied for @p count parameters. */
  static uint16_t footprint(uint8_t count) { return static_cast<uint16_t>(7u + 4u * count); }

 private:
  EepromDevice& eeprom_;
  uint16_t base_;
};

/**
 * Wear-levelled storage for a small record that changes often (the production
 * progress, saved every few minutes so a power cut does not restart a 3-hour
 * electrolysis run). Each save goes to the next of @c slotCount slots, which
 * multiplies EEPROM life by the slot count; a save interrupted by a power cut
 * only damages the slot being written, and load() falls back to the previous
 * one.
 *
 * Slot layout: sequence (2) | payload (n) | CRC-8 (1).
 */
class RingRecordStore {
 public:
  RingRecordStore(EepromDevice& eeprom, uint16_t baseAddress, uint8_t slotCount, uint8_t payloadSize);

  /** Copies the newest valid record into @p payload. @return false if none exists. */
  bool load(void* payload);

  /** Appends a new record (overwrites the oldest slot). */
  void save(const void* payload);

  /** Erases every slot (used by factory reset). */
  void clear();

  static uint16_t footprint(uint8_t slotCount, uint8_t payloadSize) {
    return static_cast<uint16_t>(slotCount * (payloadSize + 3u));
  }

 private:
  uint16_t slotAddress(uint8_t slot) const;
  bool readSlot(uint8_t slot, uint16_t& sequence, uint8_t* payload) const;
  /** Finds the newest valid slot. @return false if no slot is valid. */
  bool findNewest(uint8_t& slot, uint16_t& sequence) const;

  EepromDevice& eeprom_;
  uint16_t base_;
  uint8_t slotCount_;
  uint8_t payloadSize_;
  uint8_t nextSlot_;
  uint16_t nextSequence_;
  bool positionKnown_;
};

}  // namespace clara

#endif  // CLARA_EEPROM_STORE_H
