// Generated by tools/export_arduino.py - do not edit, edit lib/ and src/ instead.
#include "fixed_format.h"

#include <math.h>
#include <string.h>

#include "progmem.h"

namespace clara {

namespace {

/** Copies @p text into @p buffer, truncating to fit. Returns length copied. */
uint8_t copyTruncated(char* buffer, uint8_t size, const char* text) {
  if (size == 0) return 0;
  uint8_t length = 0;
  while (text[length] != '\0' && length + 1 < size) {
    buffer[length] = text[length];
    ++length;
  }
  buffer[length] = '\0';
  return length;
}

/** Writes the decimal digits of @p value into @p out (reversed order). */
uint8_t reversedDigits(uint32_t value, char* out) {
  uint8_t count = 0;
  do {
    out[count++] = static_cast<char>('0' + value % 10u);
    value /= 10u;
  } while (value != 0);
  return count;
}

const uint32_t kPowersOfTen[] = {1ul, 10ul, 100ul, 1000ul, 10000ul, 100000ul, 1000000ul};

}  // namespace

uint8_t formatUInt(char* buffer, uint8_t size, uint32_t value) {
  char digits[10];
  const uint8_t count = reversedDigits(value, digits);
  char text[11];
  for (uint8_t i = 0; i < count; ++i) text[i] = digits[count - 1 - i];
  text[count] = '\0';
  return copyTruncated(buffer, size, text);
}

uint8_t formatFixed(char* buffer, uint8_t size, float value, uint8_t decimals) {
  if (decimals > 6) decimals = 6;
  if (isnan(value)) return copyTruncated(buffer, size, "nan");

  const bool negative = value < 0.0f;
  // Scale in double precision where available (host); on AVR double == float.
  const double scaled = fabs(static_cast<double>(value)) * kPowersOfTen[decimals] + 0.5;
  if (!(scaled < 4294967295.0)) return copyTruncated(buffer, size, "ovf");

  const uint32_t fixedPoint = static_cast<uint32_t>(scaled);
  const uint32_t integerPart = fixedPoint / kPowersOfTen[decimals];
  uint32_t fractionPart = fixedPoint % kPowersOfTen[decimals];

  char text[24];
  uint8_t length = 0;
  // Do not print "-0.00" for tiny negative values that round to zero.
  if (negative && fixedPoint != 0) text[length++] = '-';

  char digits[10];
  uint8_t count = reversedDigits(integerPart, digits);
  while (count > 0) text[length++] = digits[--count];

  if (decimals > 0) {
    text[length++] = '.';
    // Emit the fraction with leading zeros, most significant digit first.
    for (uint8_t position = decimals; position > 0; --position) {
      const uint32_t divisor = kPowersOfTen[position - 1];
      text[length++] = static_cast<char>('0' + fractionPart / divisor);
      fractionPart %= divisor;
    }
  }
  text[length] = '\0';
  return copyTruncated(buffer, size, text);
}

uint8_t appendText(char* buffer, uint8_t size, const char* text) {
  const uint8_t used = static_cast<uint8_t>(strlen(buffer));
  if (used >= size) return used;
  return static_cast<uint8_t>(used + copyTruncated(buffer + used, static_cast<uint8_t>(size - used), text));
}

uint8_t appendFlash(char* buffer, uint8_t size, const char* flashText) {
  uint8_t used = static_cast<uint8_t>(strlen(buffer));
  for (;;) {
    if (used + 1 >= size) break;
    const char c = static_cast<char>(clara_read_byte_P(flashText++));
    if (c == '\0') break;
    buffer[used++] = c;
  }
  if (used < size) buffer[used] = '\0';
  return used;
}

uint8_t appendFixed(char* buffer, uint8_t size, float value, uint8_t decimals) {
  char number[20];
  formatFixed(number, sizeof(number), value, decimals);
  return appendText(buffer, size, number);
}

uint8_t appendUInt(char* buffer, uint8_t size, uint32_t value) {
  char number[12];
  formatUInt(number, sizeof(number), value);
  return appendText(buffer, size, number);
}

}  // namespace clara
