// Generated by tools/export_arduino.py - do not edit, edit lib/ and src/ instead.
#include "text_output.h"

#include "fixed_format.h"
#include "progmem.h"

namespace clara {

void TextOutput::printFloat(float value, uint8_t decimals) {
  char buffer[20];
  formatFixed(buffer, sizeof(buffer), value, decimals);
  write(buffer);
}

void TextOutput::printUInt(uint32_t value) {
  char buffer[12];
  formatUInt(buffer, sizeof(buffer), value);
  write(buffer);
}

void TextOutput::printInt(int32_t value) {
  if (value < 0) {
    write("-");
    // Negate in unsigned arithmetic so INT32_MIN is handled correctly.
    printUInt(0u - static_cast<uint32_t>(value));
  } else {
    printUInt(static_cast<uint32_t>(value));
  }
}

void TextOutput::newline() { writeFlash(CLARA_F("\r\n")); }

void TextOutput::printLineFlash(const char* flashText) {
  writeFlash(flashText);
  newline();
}

}  // namespace clara
