// Generated by tools/export_arduino.py - do not edit, edit lib/ and src/ instead.
/**
 * @file pins.h
 * @brief Wiring of the dosing processor (ATmega328 / Arduino Uno pin numbers),
 *        as on the Clara V2 Rev 4 PCB (Clara_Standard_Board_V2.2, sheet 2).
 *
 * Jumpers for stepper operation: J16 (STEP on pin 10), J25 (DIR), J22 (ENABLE
 * on pin 2), J17 (pump relay on pin 6), J14 + J15 (I2C to the main board),
 * J19 (NaClO level from main board D9), J20 + J12 (flowmeter). J13 must be
 * OPEN: it shorts RESET to GND and stops the processor.
 */
#ifndef CLARA_DOSING_PINS_H
#define CLARA_DOSING_PINS_H

#include <Arduino.h>

namespace pins {

const uint8_t kFlowMeter = 3;       ///< Flowmeter pulse output (external interrupt INT1).
const uint8_t kPumpStep = 10;       ///< Stepper driver STEP (toggled by the Timer1 interrupt).
const uint8_t kPumpDirection = 8;   ///< Stepper driver DIR.
/// Stepper driver ENABLE, active LOW. On the Clara V2 Rev 4 PCB the enable
/// signal is PD2 (pin 2) through jumper J22 and buffer U10B to P19 "Enable";
/// v2.2 used pin 7, which is not connected on that board.
const uint8_t kPumpEnable = 2;
const uint8_t kPumpRelay = 6;       ///< Pump power relay, HIGH = powered.
const uint8_t kChemicalLevel = A3;  ///< NaClO tank level from main board pin 9, HIGH = available.

/** DIR level for forward pumping. v2.2 effectively drove DIR HIGH (pump.cpp). */
const uint8_t kPumpForward = HIGH;

}  // namespace pins

#endif  // CLARA_DOSING_PINS_H
