// Generated by tools/export_arduino.py - do not edit, edit lib/ and src/ instead.
#include "telemetry_slave.h"

#include <Wire.h>
#include <string.h>
#include <util/atomic.h>

#include "src/clara/dosing_link.h"

namespace {

// The frame is written by loop() and read by the TWI interrupt; publish()
// copies it with interrupts disabled so a request never sees half a frame.
uint8_t gFrame[clara::link::kTelemetryFrameSize];
volatile uint32_t gRequests = 0;

void onRequest() {
  Wire.write(gFrame, sizeof(gFrame));
  ++gRequests;
}

void onReceive(int count) {
  // The master sends nothing in protocol v3; drain anything (e.g. from an old
  // v2.2 main board) so the bus is never left waiting.
  while (count-- > 0 && Wire.available() > 0) Wire.read();
}

}  // namespace

void I2cTelemetrySlave::begin() {
  Wire.begin(clara::link::kDosingBoardAddress);
  Wire.onRequest(onRequest);
  Wire.onReceive(onReceive);
}

uint32_t I2cTelemetrySlave::requestCount() const {
  uint32_t count;
  ATOMIC_BLOCK(ATOMIC_RESTORESTATE) { count = gRequests; }
  return count;
}

void I2cTelemetrySlave::publish(const uint8_t* frame, uint8_t length) {
  if (length != sizeof(gFrame)) return;
  ATOMIC_BLOCK(ATOMIC_RESTORESTATE) { memcpy(gFrame, frame, sizeof(gFrame)); }
}
