// Generated by tools/export_arduino.py - do not edit, edit lib/ and src/ instead.
/**
 * @file eeprom_device.h
 * @brief EepromDevice backed by the AVR's internal EEPROM.
 */
#ifndef CLARA_ARDUINO_EEPROM_DEVICE_H
#define CLARA_ARDUINO_EEPROM_DEVICE_H

#if defined(ARDUINO)
#include <EEPROM.h>

#include "../eeprom_store.h"

namespace clara {

class ArduinoEeprom : public EepromDevice {
 public:
  uint8_t read(uint16_t address) const override { return EEPROM.read(address); }
  void update(uint16_t address, uint8_t value) override { EEPROM.update(address, value); }
  uint16_t size() const override { return static_cast<uint16_t>(EEPROM.length()); }
};

}  // namespace clara

#endif  // ARDUINO
#endif  // CLARA_ARDUINO_EEPROM_DEVICE_H
