#!/usr/bin/env python3
"""Generates self-contained Arduino IDE sketches in arduino/.

The sources of truth are lib/ and src/ (used by PlatformIO and the tests). This
script copies what each board needs into one sketch folder, so the Arduino IDE
needs no extra Clara libraries:

    arduino/ClaraDosing/ClaraDosing.ino         -> Arduino Uno
    arduino/ClaraMainboard/ClaraMainboard.ino   -> Arduino Mega 2560

The Arduino IDE compiles everything in a sketch's src/ folder, but it does not
add that folder to the include path, so every '#include "clara/..."' is
rewritten to a path relative to the including file.

Run it after every change to lib/ or src/:

    python3 tools/export_arduino.py
    python3 tools/export_arduino.py --check   # CI: fail if arduino/ is out of date
"""
import filecmp
import os
import pathlib
import re
import shutil
import sys
import tempfile

ROOT = pathlib.Path(__file__).resolve().parent.parent
INCLUDE = re.compile(r'#include "(clara/[^"]+)"')

SKETCHES = {
    # sketch name: (folder in src/, libraries in lib/, board)
    "ClaraDosing": ("dosing", ["clara_common", "clara_dosing"], "Arduino Uno"),
    "ClaraMainboard": ("mainboard", ["clara_common", "clara_mainboard"], "Arduino Mega or Mega 2560"),
}

GENERATED = "Generated by tools/export_arduino.py - do not edit, edit lib/ and src/ instead."


def rewrite_includes(text: str, file_dir: pathlib.Path, sketch_src: pathlib.Path) -> str:
    def replace(match: re.Match) -> str:
        target = sketch_src / match.group(1)
        return '#include "%s"' % os.path.relpath(target, file_dir).replace(os.sep, "/")

    return INCLUDE.sub(replace, text)


def write_source(source: pathlib.Path, destination: pathlib.Path, sketch_src: pathlib.Path) -> None:
    destination.parent.mkdir(parents=True, exist_ok=True)
    text = source.read_text()
    text = rewrite_includes(text, destination.parent, sketch_src)
    destination.write_text(f"// {GENERATED}\n{text}")


def export_sketch(out: pathlib.Path, sketch: str, source_dir: str, libraries: list, board: str) -> None:
    target = out / sketch
    sketch_src = target / "src"
    for library in libraries:
        library_src = ROOT / "lib" / library / "src"
        for source in sorted(library_src.rglob("*")):
            if source.suffix in (".h", ".cpp"):
                write_source(source, sketch_src / source.relative_to(library_src), sketch_src)
    for source in sorted((ROOT / "src" / source_dir).iterdir()):
        name = f"{sketch}_main.cpp" if source.name == "main.cpp" else source.name
        write_source(source, target / name, sketch_src)
    # setup() and loop() are in <sketch>_main.cpp; the .ino only has to exist.
    (target / f"{sketch}.ino").write_text(
        f"// {GENERATED}\n"
        f"//\n"
        f"// Board: {board}. The firmware is in {sketch}_main.cpp and src/.\n"
        f"// Just click Upload.\n"
    )


def export(out: pathlib.Path) -> None:
    for sketch, (source_dir, libraries, board) in SKETCHES.items():
        if (out / sketch).exists():
            shutil.rmtree(out / sketch)
        export_sketch(out, sketch, source_dir, libraries, board)


def same_tree(a: pathlib.Path, b: pathlib.Path) -> bool:
    comparison = filecmp.dircmp(a, b)
    if comparison.left_only or comparison.right_only or comparison.diff_files or comparison.funny_files:
        return False
    return all(same_tree(a / d, b / d) for d in comparison.common_dirs)


def main() -> int:
    out = ROOT / "arduino"
    if "--check" in sys.argv:
        with tempfile.TemporaryDirectory() as temp:
            export(pathlib.Path(temp))
            stale = [s for s in SKETCHES if not (out / s).exists() or not same_tree(pathlib.Path(temp) / s, out / s)]
        if stale:
            print("arduino/ is out of date, run: python3 tools/export_arduino.py (" + ", ".join(stale) + ")")
            return 1
        print("arduino/ is up to date")
        return 0
    export(out)
    print("Arduino sketches written to arduino/")
    return 0


if __name__ == "__main__":
    sys.exit(main())
