#!/usr/bin/env python3
"""Exports the firmware in Arduino IDE / arduino-cli layout.

PlatformIO is the recommended tool (it also runs the tests), but the boards can
be built with the Arduino IDE as well:

    python3 tools/export_arduino.py            # writes build/arduino/

    build/arduino/
      libraries/clara_common/     copy these three folders into your
      libraries/clara_dosing/     Arduino "libraries" folder (Sketchbook
      libraries/clara_mainboard/  location/libraries)
      ClaraDosing/ClaraDosing.ino         open, select "Arduino Uno", upload
      ClaraMainboard/ClaraMainboard.ino   open, select "Arduino Mega 2560", upload

The main board also needs "LiquidCrystal I2C" (Frank de Brabander) from the
Library Manager. Re-run the script after every change to the sources.
"""
import pathlib
import shutil

ROOT = pathlib.Path(__file__).resolve().parent.parent
OUT = ROOT / "build" / "arduino"

LIBRARIES = {
    "clara_common": "Timing, persistence, parameters and protocol shared by the Clara boards.",
    "clara_dosing": "Dosing logic of the Clara dosing board.",
    "clara_mainboard": "Production, display and reporting logic of the Clara main board.",
}

SKETCHES = {
    "ClaraDosing": ("dosing", ["clara_common", "clara_dosing"]),
    "ClaraMainboard": ("mainboard", ["clara_common", "clara_mainboard"]),
}


def export_library(name: str, sentence: str) -> None:
    target = OUT / "libraries" / name
    shutil.copytree(ROOT / "lib" / name / "src", target / "src")
    (target / "library.properties").write_text(
        f"name={name}\nversion=3.0.0\nauthor=Clara project\nmaintainer=Clara project\n"
        f"sentence={sentence}\nparagraph=Generated by tools/export_arduino.py - do not edit.\n"
        "category=Other\nurl=https://github.com/abdisag1/Clara_heks_hudat_main\narchitectures=avr\n"
    )
    # The Arduino builder finds a library through a header in its src/ root;
    # the sketch includes this one so that "clara/..." paths resolve.
    (target / "src" / f"{name}.h").write_text(f"// Marker header so the Arduino builder links {name}.\n")


def export_sketch(sketch: str, source_dir: str, libraries: list) -> None:
    target = OUT / sketch
    target.mkdir(parents=True)
    for path in (ROOT / "src" / source_dir).iterdir():
        name = f"{sketch}_main.cpp" if path.name == "main.cpp" else path.name
        shutil.copy(path, target / name)
    # setup() and loop() stay in the .cpp: the IDE's .ino preprocessing
    # (automatic prototypes) is not needed and only gets in the way.
    marker_includes = "".join(f"#include <{lib}.h>\n" for lib in libraries)
    (target / f"{sketch}.ino").write_text(
        "// Generated by tools/export_arduino.py - do not edit.\n"
        f"// The firmware is in {sketch}_main.cpp (copied from src/{source_dir}/main.cpp).\n"
        "// These includes tell the Arduino builder which libraries to link.\n" + marker_includes
    )


def main() -> None:
    if OUT.exists():
        shutil.rmtree(OUT)
    for name, sentence in LIBRARIES.items():
        export_library(name, sentence)
    for sketch, (source_dir, libraries) in SKETCHES.items():
        export_sketch(sketch, source_dir, libraries)
    print(f"Arduino export written to {OUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
