// Generated by tools/export_arduino.py - do not edit, edit lib/ and src/ instead.
#include "dose_calculator.h"

#include "dosing_params.h"

namespace clara {
namespace dosing {

float doseRatioMlPerL(float targetFrcMgL, float naclOStrengthGL) {
  if (!(naclOStrengthGL > 0.0f) || !(targetFrcMgL > 0.0f)) return 0.0f;
  return targetFrcMgL / naclOStrengthGL;
}

float flowCoefficient(const DoseSettings& settings, float averageFlowLpm) {
  return averageFlowLpm <= settings.coefBandLpm ? settings.coefLowFlow : settings.coefHighFlow;
}

float naclOVolumeMl(const DoseSettings& settings, float waterLiters, float averageFlowLpm) {
  if (!(waterLiters > 0.0f)) return 0.0f;
  return waterLiters * doseRatioMlPerL(settings.targetFrcMgL, settings.naclOStrengthGL) *
         flowCoefficient(settings, averageFlowLpm);
}

float stepsPerMl(float stepsPerRevolution, float mlPerRevolution) {
  if (!(mlPerRevolution > 0.0f) || !(stepsPerRevolution > 0.0f)) return 0.0f;
  return stepsPerRevolution / mlPerRevolution;
}

float mlPerRevFromMeasurement(float revolutions, float measuredMl) {
  if (!(revolutions > 0.0f) || !(measuredMl > 0.0f)) return 0.0f;
  return measuredMl / revolutions;
}

uint32_t StepQuantizer::toSteps(float volumeMl, float stepsPerMlValue) {
  if (!(volumeMl > 0.0f) || !(stepsPerMlValue > 0.0f)) return 0;
  const float exact = volumeMl * stepsPerMlValue + remainder_;
  const uint32_t whole = static_cast<uint32_t>(exact);
  remainder_ = exact - static_cast<float>(whole);
  return whole;
}

DoseSettings doseSettingsFromParams(const ParamStore& params) {
  DoseSettings settings;
  settings.targetFrcMgL = params.get(kTargetFrc);
  settings.naclOStrengthGL = params.get(kNaclOStrength);
  settings.coefLowFlow = params.get(kCoefLowFlow);
  settings.coefHighFlow = params.get(kCoefHighFlow);
  settings.coefBandLpm = params.get(kCoefBandLpm);
  settings.stepsPerMl = stepsPerMl(params.get(kPumpStepsPerRev), params.get(kPumpMlPerRev));
  return settings;
}

}  // namespace dosing
}  // namespace clara
