// Generated by tools/export_arduino.py - do not edit, edit lib/ and src/ instead.
/**
 * @file dosing_app.h
 * @brief The dosing board application: ties flow measurement, dose control,
 *        the pump, calibration and telemetry together.
 */
#ifndef CLARA_DOSING_APP_H
#define CLARA_DOSING_APP_H

#include <stdint.h>

#include "../clock.h"
#include "../digital_io.h"
#include "dosing_engine.h"
#include "dosing_hal.h"
#include "dosing_params.h"
#include "flow_measurement.h"
#include "../dosing_link.h"
#include "../eeprom_store.h"
#include "../param_store.h"
#include "../periodic_timer.h"

namespace clara {
namespace dosing {

/** EEPROM map of the dosing board. */
const uint16_t kEepromParamsAddress = 0;

/** Flow sampling / telemetry period. */
const uint32_t kFlowSamplePeriodMs = 1000;

enum Mode {
  kModeAutomatic = 0,   ///< Normal flow-proportional dosing.
  kModeManualDose,      ///< Operator-requested fixed volume ("dose" command).
  kModePumpCalibration, ///< Running a known number of revolutions ("pumpcal").
};

/** Snapshot of the application state for the console and tests. */
struct DosingStatus {
  Mode mode;
  bool chemicalAvailable;
  bool flowSimulated;
  float simulatedFlowLpm;
  float frequencyHz;          ///< Measured flowmeter frequency.
  float flowLpm;              ///< Flow used for dosing (measured or simulated).
  float totalWaterLiters;     ///< Since start-up.
  float totalNaclOMl;         ///< Pumped into the water since start-up (automatic mode only).
  DoseDecision lastDecision;  ///< Result of the latest dosing interval.
  uint32_t decisionCount;     ///< Increments with every interval (console logging).
  bool saturated;             ///< Latest interval exceeded the pump's speed.
  ParamPersistence::LoadResult calibrationLoad;
  bool flowCalibrationActive;
  uint32_t flowCalibrationPulses;
  float pumpCalibrationRevs;  ///< Revolutions of the last pumpcal run (0 = none).
};

class DosingApp {
 public:
  DosingApp(const Clock& clock, FlowSensor& flowSensor, PumpDriver& pump, DigitalInput& chemicalLevel,
            EepromDevice& eeprom, TelemetrySink& telemetry);

  /** Loads the calibration from EEPROM and starts the control loop. */
  void begin();

  /** Runs one pass of the control loop; call from loop() as often as possible. */
  void update();

  // --- Calibration parameters ------------------------------------------------
  ParamStore& params() { return params_; }
  /** Saves the parameters to EEPROM and applies them to the running loop. */
  void saveAndApplyParams();

  // --- Bench tests and calibration (console commands) ------------------------
  /** Pumps @p ml of NaClO at the test speed (automatic dosing paused). */
  bool dispense(float ml);
  /** Runs the pump for @p revolutions so the output can be measured. */
  bool startPumpCalibration(float revolutions);
  /**
   * Completes a pump calibration with the volume measured by the operator.
   * @return false if no calibration run has completed or the result is out of range.
   */
  bool finishPumpCalibration(float measuredMl, float& mlPerRev);
  /** Stops any pump activity and returns to automatic mode. */
  void stopPump();

  /** Replaces the flowmeter by a fixed flow (bench test without water). */
  void setFlowSimulation(bool enabled, float flowLpm);

  /** Starts counting flowmeter pulses for a bucket test. */
  void startFlowCalibration();
  /**
   * Completes the bucket test: sets flow_k from the pulses counted and resets
   * the linear correction to identity (a one-point calibration replaces it).
   */
  bool finishFlowCalibration(float liters, float& kFactor, uint32_t& pulses);
  /** Abandons a bucket test without changing the calibration. */
  void cancelFlowCalibration() { status_.flowCalibrationActive = false; }

  const DosingStatus& status() const { return status_; }
  uint32_t pendingSteps() const { return pump_.pendingSteps(); }

 private:
  void applyParams();
  void sampleFlow(uint32_t nowMs);
  void accountPumpedVolume();
  void publishTelemetry(uint32_t nowMs);
  bool startManualRun(Mode mode, uint32_t steps);

  const Clock& clock_;
  FlowSensor& flowSensor_;
  PumpDriver& pump_;
  DigitalInput& chemicalLevel_;
  TelemetrySink& telemetry_;

  float paramValues_[kParamCount];
  ParamStore params_;
  ParamPersistence persistence_;

  FlowCalibration flowCalibration_;
  PulseFrequencyMeter frequencyMeter_;
  VolumeTotalizer totalWater_;
  VolumeTotalizer totalNaclOMicroLiters_;
  PeriodicTimer flowTimer_;
  uint32_t lastFlowSampleMs_;

  DosingEngine engine_;
  uint32_t executedStepsSeen_;
  uint32_t flowCalibrationStartCount_;
  uint8_t telemetrySequence_;
  DosingStatus status_;
};

}  // namespace dosing
}  // namespace clara

#endif  // CLARA_DOSING_APP_H
