// Generated by tools/export_arduino.py - do not edit, edit lib/ and src/ instead.
#include "step_timer.h"

namespace clara {
namespace dosing {

Timer1Setting timer1ForStepRate(uint32_t cpuHz, uint32_t stepRateHz) {
  static const uint16_t kPrescalers[] = {1, 8, 64, 256, 1024};
  static const uint8_t kClockSelect[] = {1, 2, 3, 4, 5};

  Timer1Setting setting = {0, 0, 0};
  if (stepRateHz == 0 || cpuHz == 0) return setting;

  // Two interrupts (rising and falling edge) per step.
  const uint32_t interruptHz = 2u * stepRateHz;
  for (uint8_t i = 0; i < sizeof(kPrescalers) / sizeof(kPrescalers[0]); ++i) {
    const uint32_t timerHz = cpuHz / kPrescalers[i];
    // Nearest-integer number of ticks per interrupt.
    const uint32_t ticks = (timerHz + interruptHz / 2u) / interruptHz;
    if (ticks >= 2u && ticks <= 65536u) {
      setting.prescaler = kPrescalers[i];
      setting.clockSelect = kClockSelect[i];
      setting.compareValue = static_cast<uint16_t>(ticks - 1u);
      return setting;
    }
  }
  return setting;  // too fast (or too slow) for Timer1
}

float actualStepRate(uint32_t cpuHz, const Timer1Setting& setting) {
  if (setting.prescaler == 0) return 0.0f;
  const float interruptHz =
      static_cast<float>(cpuHz) / (static_cast<float>(setting.prescaler) * (setting.compareValue + 1.0f));
  return interruptHz / 2.0f;
}

}  // namespace dosing
}  // namespace clara
