// Generated by tools/export_arduino.py - do not edit, edit lib/ and src/ instead.
/**
 * @file display_pages.h
 * @brief Content of the 20x4 LCD, rendered into plain text lines.
 *
 * Rendering is separated from the LCD driver so the exact screen content is
 * unit tested. Lines are always padded to 20 characters: the driver overwrites
 * them in place instead of calling lcd.clear(), which removes the flicker of
 * v2.2 and avoids String heap fragmentation.
 */
#ifndef CLARA_DISPLAY_PAGES_H
#define CLARA_DISPLAY_PAGES_H

#include <stdint.h>

#include "production_cycle.h"

namespace clara {
namespace mainboard {

const uint8_t kLcdColumns = 20;
const uint8_t kLcdRows = 4;
const uint8_t kPageCount = 2;

typedef char LcdLine[kLcdColumns + 1];

struct DisplayModel {
  bool splash;              ///< Start-up instructions screen.
  ProcessState state;
  uint16_t remainingMin;    ///< Time left in the current phase.
  bool linkOk;              ///< Dosing board answering.
  bool chemicalAvailable;   ///< NaClO tank level (dosing board view).
  bool pumpSaturated;       ///< Dosing pump at max speed: under-dosing.
  float flowLpm;
  float lastDoseMl;         ///< NaClO injected in the last dosing interval.
  float totalWaterM3;
  float targetFrcMgL;
  float voltage;
  bool level1;
  bool level2;
  bool level3;
};

/** Renders page @p page (0 .. kPageCount-1) of @p model into @p lines. */
void renderPage(const DisplayModel& model, uint8_t page, LcdLine lines[kLcdRows]);

}  // namespace mainboard
}  // namespace clara

#endif  // CLARA_DISPLAY_PAGES_H
