// Generated by tools/export_arduino.py - do not edit, edit lib/ and src/ instead.
#include "mainboard_app.h"

#include "../byte_codec.h"
#include "voltage.h"

namespace clara {
namespace mainboard {

namespace {

// v2.2 stored its "set 1" / "set 2" values (settling and transfer minutes) as
// floats at these EEPROM addresses. The production time at address 0 is not
// imported: v2.2 overwrote it with the remaining time of the running batch.
const uint16_t kLegacySettlingAddress = 4;
const uint16_t kLegacyTransferAddress = 8;

float readLegacyFloat(const EepromDevice& eeprom, uint16_t address) {
  uint8_t bytes[4];
  for (uint8_t i = 0; i < 4; ++i) bytes[i] = eeprom.read(static_cast<uint16_t>(address + i));
  return getF32(bytes);
}

}  // namespace

MainboardApp::MainboardApp(const Clock& clock, MainboardIo& io, DosingLinkPort& link, CharacterDisplay& display,
                           TextOutput& ecophi, EepromDevice& eeprom)
    : clock_(clock),
      io_(io),
      link_(link),
      display_(display),
      ecophi_(ecophi),
      eeprom_(eeprom),
      params_(parameterTable(), kParamCount, paramValues_),
      persistence_(eeprom, kEepromParamsAddress),
      progressStore_(eeprom, kEepromProgressAddress, kProgressSlots, kCycleProgressSize),
      sensorTimer_(kSensorPeriodMs),
      voltageTimer_(kVoltageSamplePeriodMs),
      linkTimer_(kLinkPollPeriodMs),
      displayTimer_(kDisplayRefreshMs),
      reportTimer_(60000),
      voltageAdcSum_(0),
      voltageSamples_(0),
      lastLinkOkMs_(0),
      everLinked_(false),
      bootMs_(0),
      status_() {}

void MainboardApp::begin() {
  const uint32_t nowMs = clock_.millis();
  bootMs_ = nowMs;

  loadCalibration();
  applyParams();

  // Resume an interrupted batch, if any.
  uint8_t saved[kCycleProgressSize];
  if (progressStore_.load(saved)) {
    CycleProgress progress = decodeProgress(saved);
    const bool interrupted = progress.state != kStateStandby;
    if (interrupted && params_.get(kResumeBatch) < 0.5f) {
      // Resume disabled: start in standby, but keep the batch counter and the
      // electrode polarity so the reversal schedule stays correct.
      progress.state = kStateStandby;
      progress.elapsedMinutes = 0;
      status_.progressDiscarded = true;
    }
    cycle_.restore(progress, nowMs);
    status_.progressRestored = cycle_.state() != kStateStandby;
    if (status_.progressDiscarded) persistProgress(nowMs, true);
  } else {
    cycle_.begin(nowMs);
  }
  io_.applyOutputs(cycle_.outputs());

  // Level sensors start "empty"; they must be stable for level_debounce seconds.
  for (uint8_t i = 0; i < kLevelSensorCount; ++i) levelFilters_[i].reset(false);
  io_.setChemicalAvailableSignal(false);

  sensorTimer_.start(nowMs);
  voltageTimer_.start(nowMs);
  linkTimer_.start(nowMs);
  displayTimer_.start(nowMs);
  reportTimer_.start(nowMs);
  dosedRate_.start(nowMs);
}

void MainboardApp::loadCalibration() {
  status_.calibrationLoad = persistence_.load(params_);
  if (status_.calibrationLoad == ParamPersistence::kLoadExtended) {
    // Saved by a firmware with fewer parameters: keep the values, add the new defaults.
    persistence_.save(params_);
    status_.calibrationLoad = ParamPersistence::kLoadOk;
  }
  if (status_.calibrationLoad == ParamPersistence::kLoadEmpty) importLegacySettings();
}

void MainboardApp::importLegacySettings() {
  const float settling = readLegacyFloat(eeprom_, kLegacySettlingAddress);
  const float transfer = readLegacyFloat(eeprom_, kLegacyTransferAddress);
  if (params_.isValid(kSettlingMin, settling) && params_.isValid(kTransferMin, transfer)) {
    params_.set(kSettlingMin, settling);
    params_.set(kTransferMin, transfer);
    persistence_.save(params_);
    status_.calibrationLoad = ParamPersistence::kLoadOk;
    status_.legacyImported = true;
  }
}

void MainboardApp::applyParams() {
  CycleTimes times;
  times.productionMs = static_cast<uint32_t>(params_.get(kProductionMin)) * 60000ul;
  times.settlingMs = static_cast<uint32_t>(params_.get(kSettlingMin)) * 60000ul;
  times.transferMs = static_cast<uint32_t>(params_.get(kTransferMin)) * 60000ul;
  times.polarityCycles = static_cast<uint8_t>(params_.get(kPolarityCycles));
  cycle_.configure(times);

  const uint8_t debounceSamples = static_cast<uint8_t>(params_.get(kLevelDebounceS) * 1000.0f / kSensorPeriodMs);
  for (uint8_t i = 0; i < kLevelSensorCount; ++i) levelFilters_[i].setRequiredSamples(debounceSamples);

  reportTimer_.setPeriod(static_cast<uint32_t>(params_.get(kReportIntervalS)) * 1000ul);
}

void MainboardApp::saveAndApplyParams() {
  persistence_.save(params_);
  status_.calibrationLoad = ParamPersistence::kLoadOk;
  applyParams();
}

void MainboardApp::update() {
  const uint32_t nowMs = clock_.millis();

  if (voltageTimer_.poll(nowMs)) {
    voltageAdcSum_ += io_.readVoltageAdc();
    ++voltageSamples_;
  }
  if (sensorTimer_.poll(nowMs)) sampleSensors(nowMs);
  if (linkTimer_.poll(nowMs)) pollDosingBoard(nowMs);

  CycleInputs inputs;
  inputs.productionBottleFull = status_.levels[0];
  inputs.storageTankFull = status_.levels[1];
  cycle_.update(nowMs, inputs);
  io_.applyOutputs(cycle_.outputs());
  persistProgress(nowMs);

  if (displayTimer_.poll(nowMs)) refreshDisplay(nowMs);
  if (reportTimer_.poll(nowMs)) sendReport(nowMs);
}

void MainboardApp::sampleSensors(uint32_t nowMs) {
  (void)nowMs;
  for (uint8_t i = 0; i < kLevelSensorCount; ++i) status_.levels[i] = levelFilters_[i].update(io_.readLevelSensor(i));
  // Level sensor 3 (NaClO dosing tank) is forwarded to the dosing board, which
  // stops the pump when it is low.
  io_.setChemicalAvailableSignal(status_.levels[2]);

  if (voltageSamples_ > 0) {
    const float averageAdc = static_cast<float>(voltageAdcSum_) / voltageSamples_;
    status_.voltage = adcToVolts(averageAdc, params_.get(kVoltageRef), params_.get(kVoltageDivider));
    voltageAdcSum_ = 0;
    voltageSamples_ = 0;
  }

  averager_.addSample(status_.linkOk ? status_.dosing.flowLpm : 0.0f, 0.0f, 0.0f);
}

void MainboardApp::pollDosingBoard(uint32_t nowMs) {
  uint8_t frame[link::kTelemetryFrameSize + 4];
  const uint8_t received = link_.requestFrame(frame, sizeof(frame));
  link::DosingTelemetry telemetry;
  if (received > 0 && link::decodeTelemetry(frame, received, telemetry) == link::kDecodeOk) {
    status_.dosing = telemetry;
    lastLinkOkMs_ = nowMs;
    everLinked_ = true;
  } else {
    ++status_.linkErrors;
  }
  status_.linkOk = everLinked_ && nowMs - lastLinkOkMs_ < kLinkTimeoutMs;
}

void MainboardApp::refreshDisplay(uint32_t nowMs) {
  DisplayModel model;
  model.splash = nowMs - bootMs_ < kSplashMs;
  model.state = cycle_.state();
  model.remainingMin = cycle_.remainingMinutes(nowMs);
  model.linkOk = status_.linkOk;
  model.chemicalAvailable = (status_.dosing.flags & link::kFlagChemicalAvailable) != 0;
  model.pumpSaturated = (status_.dosing.flags & link::kFlagPumpSaturated) != 0;
  model.flowLpm = status_.dosing.flowLpm;
  model.lastDoseMl = status_.dosing.lastDoseMl;
  model.totalWaterM3 = static_cast<float>(status_.dosing.totalWaterL) / 1000.0f;
  model.targetFrcMgL = status_.dosing.targetFrcMgL;
  model.voltage = status_.voltage;
  model.level1 = status_.levels[0];
  model.level2 = status_.levels[1];
  model.level3 = status_.levels[2];

  const uint8_t page = static_cast<uint8_t>(((nowMs - bootMs_) / kDisplayPageMs) % kPageCount);
  LcdLine lines[kLcdRows];
  renderPage(model, page, lines);
  for (uint8_t row = 0; row < kLcdRows; ++row) display_.writeLine(row, lines[row]);
}

void MainboardApp::sendReport(uint32_t nowMs) {
  EcophiFrame frame;
  frame.flowLpm = averager_.averageFlowLpm();
  frame.voltage = status_.voltage;
  frame.level1 = status_.levels[0];
  frame.level2 = status_.levels[1];
  frame.level3 = status_.levels[2];
  frame.naclOMlPerMin = dosedRate_.takeRate(status_.dosing.totalNaclOMicroL, status_.linkOk, nowMs);
  frame.targetFrcMgL = status_.dosing.targetFrcMgL;
  frame.activeChlorine = averager_.averageActiveChlorine();
  frame.ph = averager_.averagePh();
  averager_.reset();

  char text[kEcophiFrameCapacity];
  formatEcophiFrame(frame, text, sizeof(text));
  ecophi_.write(text);
}

void MainboardApp::sendReportNow() {
  const uint32_t nowMs = clock_.millis();
  sendReport(nowMs);
  reportTimer_.start(nowMs);
}

void MainboardApp::forceState(ProcessState state) {
  const uint32_t nowMs = clock_.millis();
  cycle_.forceState(state, nowMs);
  io_.applyOutputs(cycle_.outputs());
  persistProgress(nowMs, true);
}

void MainboardApp::persistProgress(uint32_t nowMs, bool force) {
  if (!cycle_.takePersistRequest(nowMs) && !force) return;
  uint8_t bytes[kCycleProgressSize];
  encodeProgress(cycle_.progress(nowMs), bytes);
  progressStore_.save(bytes);
}

}  // namespace mainboard
}  // namespace clara
