// Generated by tools/export_arduino.py - do not edit, edit lib/ and src/ instead.
/**
 * @file mainboard_hal.h
 * @brief Hardware interfaces required by the main-board application.
 */
#ifndef CLARA_MAINBOARD_HAL_H
#define CLARA_MAINBOARD_HAL_H

#include <stdint.h>

#include "production_cycle.h"

namespace clara {
namespace mainboard {

const uint8_t kLevelSensorCount = 3;

/** Sensors and actuators of the production unit. */
class MainboardIo {
 public:
  /** Raw state of level sensor @p index (0 = production bottle, 1 = storage tank, 2 = NaClO dosing tank). */
  virtual bool readLevelSensor(uint8_t index) = 0;
  /** Raw 10-bit ADC reading of the voltage sensor. */
  virtual uint16_t readVoltageAdc() = 0;
  /** Drives electrolysis, fan, polarity and transfer valve. */
  virtual void applyOutputs(const CycleOutputs& outputs) = 0;
  /** Signal to the dosing board that NaClO is available (wire to its A3 input). */
  virtual void setChemicalAvailableSignal(bool available) = 0;

 protected:
  ~MainboardIo() {}
};

/** Transport of telemetry frames from the dosing board (I2C master on target). */
class DosingLinkPort {
 public:
  /**
   * Requests one frame. @return number of bytes received into @p buffer
   * (0 if the dosing board did not answer).
   */
  virtual uint8_t requestFrame(uint8_t* buffer, uint8_t capacity) = 0;

 protected:
  ~DosingLinkPort() {}
};

/** A character display with fixed-width lines. */
class CharacterDisplay {
 public:
  /** Writes @p text (exactly kLcdColumns characters) to @p row. */
  virtual void writeLine(uint8_t row, const char* text) = 0;

 protected:
  ~CharacterDisplay() {}
};

}  // namespace mainboard
}  // namespace clara

#endif  // CLARA_MAINBOARD_HAL_H
