// Generated by tools/export_arduino.py - do not edit, edit lib/ and src/ instead.
#include "mainboard_console.h"

#include "../progmem.h"

namespace clara {
namespace mainboard {

namespace {

const uint8_t kMaxTokens = 4;

bool is(const char* token, const char* flashText) { return clara_strcasecmp_P(token, flashText) == 0; }

}  // namespace

MainboardConsole::MainboardConsole(MainboardApp& app, TextOutput& out)
    : app_(app), out_(out), reader_(), paramConsole_(app.params(), out) {}

void MainboardConsole::printBanner() {
  // No ';' in console output: the Ecophi receiver on the shared line ignores it.
  out_.printFlash(CLARA_F("Clara main board v3.0 - type help - "));
  out_.printUInt(app_.serialBaudRate());
  out_.printLineFlash(CLARA_F(" baud"));
  const MainboardStatus& status = app_.status();
  if (status.legacyImported) out_.printLineFlash(CLARA_F("imported settling and transfer time from v2.2"));
  if (status.calibrationLoad != ParamPersistence::kLoadOk) {
    out_.printLineFlash(CLARA_F("warning - no valid calibration in EEPROM, defaults in use"));
  }
  if (status.progressRestored) {
    out_.printLineFlash(CLARA_F("resumed the batch interrupted by a power cut"));
    out_.printLineFlash(CLARA_F("  type cancel to abandon it, or set resume_batch 0 to never resume"));
  }
  if (status.progressDiscarded) out_.printLineFlash(CLARA_F("interrupted batch not resumed (resume_batch = 0)"));
}

void MainboardConsole::onChar(char c) {
  if (reader_.push(c)) execute(reader_.line());
}

void MainboardConsole::execute(char* line) {
  char* tokens[kMaxTokens];
  const uint8_t count = splitTokens(line, tokens, kMaxTokens);
  if (count == 0) return;

  // report_baud only accepts the standard rates.
  if (count == 3 && is(tokens[0], CLARA_F("set")) && app_.params().find(tokens[1]) == kReportBaud) {
    float baud = 0.0f;
    if (!parseFloat(tokens[2], baud) || !isStandardBaudRate(baud)) {
      out_.printLineFlash(CLARA_F("error: use 9600, 19200, 38400, 57600 or 115200"));
      return;
    }
    if (baud != app_.params().get(kReportBaud)) {
      out_.printFlash(CLARA_F("ok - switching to "));
      out_.printUInt(static_cast<uint32_t>(baud));
      out_.printLineFlash(CLARA_F(" baud now, change the Serial Monitor and the Ecophi unit too"));
    }
  }

  bool changed = false;
  if (paramConsole_.handle(tokens, count, changed)) {
    if (changed) app_.saveAndApplyParams();
    return;
  }

  if (is(tokens[0], CLARA_F("help")) || is(tokens[0], CLARA_F("cal"))) {
    printHelp();
  } else if (is(tokens[0], CLARA_F("status"))) {
    printStatus();
  } else if (is(tokens[0], CLARA_F("force"))) {
    handleForce(tokens, count);
  } else if (is(tokens[0], CLARA_F("i2c"))) {
    scanBus();
  } else if (is(tokens[0], CLARA_F("cancel"))) {
    app_.cancelBatch();
    out_.printLineFlash(CLARA_F("ok - batch cancelled, standby (will not resume after power-up)"));
  } else if (is(tokens[0], CLARA_F("report"))) {
    app_.sendReportNow();
    out_.newline();
  } else {
    out_.printLineFlash(CLARA_F("unknown command, type help"));
  }
}

void MainboardConsole::printHelp() {
  out_.printLineFlash(CLARA_F("Clara main board commands"));
  out_.printLineFlash(CLARA_F("  status                live values"));
  paramConsole_.printHelp();
  out_.printLineFlash(CLARA_F("  cancel                abandon the running batch (standby)"));
  out_.printLineFlash(CLARA_F("  i2c                   list devices on the I2C bus"));
  out_.printLineFlash(CLARA_F("  force <standby|production|settling|transfer>"));
  out_.printLineFlash(CLARA_F("                        jump to a state (bench test)"));
  out_.printLineFlash(CLARA_F("  report                send an Ecophi frame now"));
  out_.printLineFlash(CLARA_F("Dosing calibration is done on the dosing board USB port."));
}

void MainboardConsole::printStatus() {
  const MainboardStatus& s = app_.status();
  const ProductionCycle& cycle = app_.cycle();
  const uint32_t nowMs = app_.now();

  out_.printFlash(CLARA_F("state: "));
  out_.printFlash(stateName(cycle.state()));
  out_.printFlash(CLARA_F("  remaining "));
  out_.printUInt(cycle.remainingMs(nowMs) / 1000u);
  out_.printFlash(CLARA_F(" s  batches "));
  out_.printUInt(cycle.completedCycles());
  out_.printFlash(cycle.outputs().polarityReversed ? CLARA_F("  polarity reversed") : CLARA_F("  polarity normal"));
  out_.newline();

  out_.printFlash(CLARA_F("levels L1 "));
  out_.printUInt(s.levels[0]);
  out_.printFlash(CLARA_F(" L2 "));
  out_.printUInt(s.levels[1]);
  out_.printFlash(CLARA_F(" L3 "));
  out_.printUInt(s.levels[2]);
  out_.printFlash(CLARA_F("   voltage "));
  out_.printFloat(s.voltage, 2);
  out_.printLineFlash(CLARA_F(" V"));

  out_.printFlash(CLARA_F("dosing link "));
  out_.printFlash(s.linkOk ? CLARA_F("ok") : CLARA_F("LOST"));
  out_.printFlash(CLARA_F(" (errors "));
  out_.printUInt(s.linkErrors);
  out_.printLineFlash(CLARA_F(")"));
  if (!s.linkOk) printLinkDiagnosis();
  if (s.linkOk) {
    out_.printFlash(CLARA_F("  flow "));
    out_.printFloat(s.dosing.flowLpm, 2);
    out_.printFlash(CLARA_F(" L/min  last dose "));
    out_.printFloat(s.dosing.lastDoseMl, 2);
    out_.printFlash(CLARA_F(" mL  water "));
    out_.printUInt(s.dosing.totalWaterL);
    out_.printFlash(CLARA_F(" L  NaClO "));
    out_.printFloat(static_cast<float>(s.dosing.totalNaclOMicroL) / 1000.0f, 1);
    out_.printLineFlash(CLARA_F(" mL"));
    if (s.dosing.flags & link::kFlagPumpSaturated) out_.printLineFlash(CLARA_F("  WARNING pump saturated"));
    if (s.dosing.flags & link::kFlagConfigDefaults) {
      out_.printLineFlash(CLARA_F("  WARNING dosing board uses default calibration"));
    }
    if (s.dosing.flags & link::kFlagFlowSimulated) out_.printLineFlash(CLARA_F("  NOTE flow is simulated"));
  }
}

void MainboardConsole::printLinkDiagnosis() {
  const MainboardStatus& s = app_.status();
  out_.printFlash(CLARA_F("  last poll - "));
  if (s.lastLinkBytes == 0) {
    out_.printLineFlash(CLARA_F("NO ANSWER from address 0x21"));
    out_.printLineFlash(CLARA_F("  the dosing processor is not on the bus - check that it runs"));
    out_.printLineFlash(CLARA_F("  (jumper J13 must be OPEN), J14 + J15 closed, then type i2c"));
    return;
  }
  out_.printUInt(s.lastLinkBytes);
  out_.printFlash(CLARA_F(" bytes, "));
  if (s.lastLinkResult == link::kDecodeBadCrc) {
    out_.printLineFlash(CLARA_F("checksum wrong"));
  } else if (s.lastLinkResult == link::kDecodeBadVersion) {
    out_.printLineFlash(CLARA_F("protocol version wrong"));
  } else {
    out_.printLineFlash(CLARA_F("frame length wrong"));
  }
  out_.printLineFlash(CLARA_F("  the dosing board answers but with other data - upload the v3"));
  out_.printLineFlash(CLARA_F("  dosing firmware (ClaraDosing) to the dosing processor"));
}

void MainboardConsole::scanBus() {
  out_.printLineFlash(CLARA_F("I2C scan"));
  uint8_t found = 0;
  for (uint8_t address = 0x08; address < 0x78; ++address) {
    if (!app_.linkPort().probe(address)) continue;
    ++found;
    out_.printFlash(CLARA_F("  0x"));
    const char digits[] = "0123456789ABCDEF";
    const char hex[3] = {digits[address >> 4], digits[address & 0x0F], '\0'};
    out_.write(hex);
    if (address == link::kDosingBoardAddress) {
      out_.printLineFlash(CLARA_F("  dosing board"));
    } else if ((address >= 0x20 && address <= 0x27) || (address >= 0x38 && address <= 0x3F)) {
      out_.printLineFlash(CLARA_F("  LCD backpack (PCF8574)"));
    } else {
      out_.printLineFlash(CLARA_F("  unknown device"));
    }
  }
  if (found == 0) out_.printLineFlash(CLARA_F("  no devices - check SDA/SCL wiring and pull-ups"));
  if (!app_.linkPort().probe(link::kDosingBoardAddress)) {
    out_.printLineFlash(CLARA_F("  dosing board (0x21) NOT found - see status for hints"));
  }
}

void MainboardConsole::handleForce(char** tokens, uint8_t count) {
  if (count == 2) {
    if (is(tokens[1], CLARA_F("standby"))) {
      app_.forceState(kStateStandby);
    } else if (is(tokens[1], CLARA_F("production"))) {
      app_.forceState(kStateProduction);
    } else if (is(tokens[1], CLARA_F("settling"))) {
      app_.forceState(kStateSettling);
    } else if (is(tokens[1], CLARA_F("transfer"))) {
      app_.forceState(kStateTransferring);
    } else {
      count = 0;  // fall through to usage
    }
    if (count == 2) {
      out_.printFlash(CLARA_F("ok - state "));
      out_.printLineFlash(stateName(app_.cycle().state()));
      return;
    }
  }
  out_.printLineFlash(CLARA_F("usage - force <standby|production|settling|transfer>"));
}

}  // namespace mainboard
}  // namespace clara
