// Generated by tools/export_arduino.py - do not edit, edit lib/ and src/ instead.
/**
 * @file main_params.h
 * @brief Calibration parameters of the main board.
 */
#ifndef CLARA_MAIN_PARAMS_H
#define CLARA_MAIN_PARAMS_H

#include <stdint.h>

#include "../param_store.h"

namespace clara {
namespace mainboard {

/** Parameter indices (console numbering). Append new entries at the end. */
enum Param {
  kProductionMin = 0,  ///< Electrolysis duration per batch, min.
  kSettlingMin,        ///< Settling time after electrolysis, min.
  kTransferMin,        ///< Valve open time to transfer the batch, min.
  kPolarityCycles,     ///< Reverse electrode polarity every N batches.
  kReportIntervalS,    ///< Ecophi report period, s.
  kLevelDebounceS,     ///< A level sensor must be stable this long to change state, s.
  kVoltageRef,         ///< ADC reference voltage as measured on the board, V.
  kVoltageDivider,     ///< Voltage sensor divider ratio (battery V per ADC V).
  kResumeBatch,        ///< 1: continue an interrupted batch after a power cut, 0: start in standby.
  kReportBaud,         ///< Baud rate of the serial port (Ecophi report + console).
  kParamCount
};

const ParamInfo* parameterTable();

/** Baud rates accepted for report_baud. */
const uint32_t kStandardBaudRates[] = {9600, 19200, 38400, 57600, 115200};
const uint32_t kDefaultBaudRate = 115200;

/** True if @p baud is one of kStandardBaudRates. */
bool isStandardBaudRate(float baud);

}  // namespace mainboard
}  // namespace clara

#endif  // CLARA_MAIN_PARAMS_H
